---
- name: Build Server 
  hosts: dev
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common
    
# artifactory & sonar use mysql, postgresql option not finished
    - mysql
#    - postgres

# nexus and artifactory can be used as library and/or build repository
    - artifactory
    - nexus

# Use Jenkins to build, so SonarQube can be used for reports
    - jenkins
    - sonar    
    - httpd

# TODO
#    - gitblit

- name: Test server 
  hosts: test
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common
#    - mysql
    - postgres
#    - docker
