---
- name: Install 
  hosts: all
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common

# artifactory & sonar use mysql, postgresql option not finished
    - mysql
#    - postgres

# TODO
#    - gitblit

# nexus and artifactory can be used as library and/or build repository
    - artifactory
    - nexus

# Use Jenkins to build, so SonarQube can be used for reports
    - jenkins
    - sonar
