---
- name: Build Server 
  hosts: dev
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common
    - httpd
    
# Use Jenkins to build
    - jenkins

# nexus can be used as library repository
    - nexus
# artifactory & sonar use mysql, postgresql option not finished
    - mysql
#    - postgres

# SonarQube can be used for reports
    - sonar   

# Artifactory can be used as build repository
    - artifactory

# Git server
#    - gitlab


- name: Test server 
  hosts: test
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common
