---
- name: Build Server 
  hosts: dev
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - bbaassssiiee.commoncentos
    - httpd
    
# Use Jenkins to build
    - jenkins

# nexus can be used as library repository
    - hullufred.nexus

# artifactory & sonar use mariadb
    - pcextreme.mariadb

# SonarQube can be used for reports
    - sonar

# Artifactory can be used as build repository
    - bbaassssiiee.artifactory


- name: Test server 
  hosts: test
  user: root
  remote_user: vagrant
  sudo: yes
  vars:
    homedir: "{{ lookup('env','HOME') }}"

  roles:
    - bbaassssiiee.commoncentos
    - geerlingguy.java
    - hudecof.tomcat

  tasks:
    - include: tasks/settings.yml
