---
- name: Install 
  hosts: all
  user: root
  remote_user: vagrant
  sudo: yes

  roles:
    - common
    - nexus
#    - mysql
    - postgres

#    - gitblit

    - jenkins
    - sonar

    - artifactory
