---
- src: bbaassssiiee.commoncentos
  path: roles/

- src: hullufred.nexus
  path: roles/

- src: geerlingguy.java
  path: roles/

- src: hudecof.tomcat
  path: roles

- src: pcextreme.mariadb
  path: roles/

