    - name: 'add "dev" in /etc/hosts file'
      lineinfile: dest=/etc/hosts regexp='192.168.10.16'
              line='192.168.10.16   dev' 
              state=present

    - name: 'add "test" in /etc/hosts file'
      lineinfile: dest=/etc/hosts regexp='192.168.10.18'
              line='192.168.10.18   test' 
              state=present

    - name: 'update apt cache'
      apt: update_cache=yes cache_valid_time=86400

    - name: 'install ubuntu-desktop (GUI)'
      apt: install_recommends=no name=ubuntu-desktop state=present

    - name: 'remove guest login'
      lineinfile: dest=/usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf regexp='^allow-guest'
              line='allow-guest=false' 
              state=present

    - name: 'install ubuntu stuff'
      apt: name={{ item }} state=present
      with_items:
        - virtualbox-guest-dkms
        - flashplugin-installer
        - git
