    - name: "download the warfile from artifactory into apache-tomcat"
      action: get_url url=http://dev/artifactory/ext-snapshot-local/gameoflife-web/target/gameoflife.war
          force=yes dest=/opt/apache-tomcat/webapps owner=tomcat group=tomcat mode=0644
      retries: 5
      delay: 10
