---
- name: 'make sure directory exists for gitblit'
  file: dest=/opt/gitblit state=directory mode=0755
  when: features.gitblit
  
- name: 'verify presence of gitblit'
  stat: path=/opt/gitblit/gitblit.jar
  register: jarfile
  when: features.gitblit

- name: 'download gitblit'
  get_url: url={{gitblit_url}} dest=/tmp
  retries: 3
  when: features.gitblit and not jarfile.stat.exists

- name: 'untar gitblit'
  command: tar xfz /tmp/{{gitblit_tarfile}} -C /opt/gitblit 
  when: features.gitblit and not jarfile.stat.exists

# TODO: service needs proper integration
#- name: 'verify presence of init script'
#  stat: path=/etc/init.d/gitblit
#  register: gitblit
#  when: features.gitblit
# 
#- name: 'install init script if needed'
#  command: cp /opt/gitblit/service-centos.sh /etc/init.d/gitblit
#  when: features.gitblit and not gitblit.stat.exists
# 
#- name: 'register gitblit as a service'
#  service: name=gitblit enabled=true
#  notify: 'restart gitblit'
#  when: features.gitblit

- name: 'verify presence of gitblit download'
  stat: path=/tmp/{{gitblit_tarfile}}
  register: gitblit_download
  when: features.gitblit

- name: 'cleanup gitblit download'
  file: dest=/tmp/{{gitblit_tarfile}} state=absent
  when: gitblit_download.stat.exists

- name: 'make sure gitblit directory is absent'
  file: dest=/opt/gitblit state=absent
  when: not features.gitblit
