---
- name: 'make sure rpm_dependencies are installed'
  yum: name={{item}} state=installed
  when: ansible_os_family == "RedHat"
  register: installed
  retries: 3
  with_items: rpm_dependencies

- name: 'install createrepo for nexus-yum-repository-plugin'
  yum: name=createrepo state=installed
  when: ansible_os_family == "RedHat"

- name: 'check if nexus_home directory exists'
  file: path={{nexus_home}} state=directory

- name: 'create nexus user'
  user: name=nexus home={{nexus_home}} generate_ssh_key=yes ssh_key_bits=2048

- name: 'verify sonatype-work/nexus directory'
  file: path={{nexus_home}}/sonatype-work/nexus owner=nexus group=nexus state=directory
  register: upgrade

- name: 'download the nexus tarball'
  get_url: url={{nexus_url}} dest=/data/{{nexus_file}} owner=root group=root mode=0700

- name: 'untar Nexus tarball in nexus_home'
  shell: tar xvzf /data/nexus-*-bundle.tar.gz -C {{nexus_home}}

- name: 'update symlink /usr/local/nexus'
  shell: ln -fs `ls -d /data/nexus/nexus-*|tail -1` /usr/local/nexus

- name: 'export NEXUS_HOME=/usr/local/nexus'
  template: src=etc-profile-d-nexus-sh.j2 dest=/etc/profile.d/nexus.sh owner=root group=root mode=0644

- name: 'create /usr/local/nexus/conf/nexus-properties'
  template: src=nexus-properties.j2 dest=/usr/local/nexus/conf/nexus.properties owner=nexus group=nexus mode=0644

#- name: 'force base url for proxy'
#  lineinfile: dest={{nexus_work}}/conf/nexus.xml regexp='forceBaseUrl' line='<forceBaseUrl>true</forceBaseUrl>' state=present

#- name: 'force checksumPolicy'
#  lineinfile: dest={{nexus_work}}/conf/nexus.xml regexp='checksumPolicy' line='<checksumPolicy>STRICT</checksumPolicy>' state=present

- name: 'copy the /etc/init.d/nexus file'
  template: src=init-nexus.j2 dest=/etc/init.d/nexus owner=root group=root mode=0755 backup=yes
  notify:
    - 'start nexus'
  tags:
    - init

- name: 'register service with chkconfig system'
  service: name=nexus enabled=yes
  tags:
    - config
    - init

- name: 'set service start/stop order'
  sudo: yes
  command: chkconfig nexus reset
  tags:
    - config
    - init

- name: 'grant ownership on directory'
  file: path=/usr/local/nexus/logs owner=nexus group=nexus state=directory

- name: 'grant ownership on nexus_work'
  file: path={{nexus_work}} owner=nexus group=nexus state=directory

- name: 'grant ownership on nexus_work'
  file: path={{nexus_home}} owner=nexus group=nexus state=directory recurse=yes

- name: 'grant ownership on pid-dir'
  file: path=/var/run/nexus owner=nexus group=nexus state=directory



