---
- name: 'install mysql packages'
  yum: name={{ item }} state=present
  with_items: mysql_packages
  when: ansible_os_family == "RedHat"

- name: 'create mysqld configuration file'
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: 'start mysqld Service'
  service: name=mysqld state=started enabled=true
