---

- name: 'create jenkins M2_HOME'
  file: state=directory dest={{jenkins_home}}/.m2/ owner=jenkins group=jenkins mode=0700
  tags:
    - config
  when: ansible_os_family == "RedHat"
  
- name: 'copy settings.xml template'
  template: src=settings_xml.j2 dest={{jenkins_home}}/.m2/settings.xml owner=jenkins group=jenkins mode=0600
  tags:
    - config
  when: ansible_os_family == "RedHat"

- name: 'install /etc/profile.d/jdk.sh'
  template: src=etc-profile-d-jdk-sh.j2 dest=/etc/profile.d/jdk.sh
          owner=root group=root mode=0644
  notify:
  - 'restart jenkins'  

- name: 'install /etc/profile.d/maven.sh'
  template: src=etc-profile-d-maven-sh.j2 dest=/etc/profile.d/maven.sh
          owner=root group=root mode=0644
  when: features.maven
  notify:
  - 'restart jenkins'  
  
- name: 'install /etc/profile.d/ant.sh'
  template: src=etc-profile-d-ant-sh.j2 dest=/etc/profile.d/ant.sh
          owner=root group=root mode=0644
  when: features.ant
  notify:
  - 'restart jenkins'
  
- name: 'install /etc/profile.d/gradle.sh'
  template: src=etc-profile-d-gradle-sh.j2 dest=/etc/profile.d/gradle.sh
          owner=root group=root mode=0644
  when: features.gradle
  notify:
  - 'restart jenkins'  
