---

- name: 'create jenkins M2_HOME'
  file: state=directory dest={{jenkins_home}}/.m2/ owner=jenkins group=jenkins mode=0700
  tags:
    - config
  when: ansible_os_family == "RedHat"
  
- name: 'create settings.xml'
  template: src=settings_xml.j2 dest={{jenkins_home}}/.m2/settings.xml owner=jenkins group=jenkins mode=0600
  tags:
    - config
  when: ansible_os_family == "RedHat"

- name: 'create jenkins config files'
  template: src={{item}} dest={{jenkins_data}}/{{item}} owner=jenkins group=jenkins mode=0600
  with_items: jenkins_configs
  tags:
    - config
  when: ansible_os_family == "RedHat"
  
