---
- name: 'make sure rpm_dependencies are installed'
  yum: name={{item}} state=installed
  when: ansible_os_family == "RedHat"
  register: installed
  retries: 3
  with_items: rpm_dependencies

- name: 'install software group "Development tools"'
  yum: name="@Development tools" state=present
  retries: 3
  when: ansible_os_family == "RedHat"

- name: 'make sure jenkins_data directory exists'
  file: path={{jenkins_data}} owner=jenkins group=jenkins state=directory

- name: 'make sure jenkins_tools directory exists'
  file: path={{jenkins_tools}} owner=jenkins group=jenkins mode=0755 state=directory
