---
### Gradle
- name: 'verify presence of Gradle'
  stat: path={{gradle_home}}/bin/gradle
  register: gradle_installed
  when: features.gradle

- name: 'download Gradle'
  get_url: url={{gradle_url}} dest=/tmp
  retries: 3
  when: features.gradle and not gradle_installed.stat.exists
  
- name: 'unzip Gradle'
  command: unzip -o  /tmp/{{gradle_zipfile}} -d {{jenkins_tools}} creates={{gradle_home}}
  when: features.gradle

- name: 'verify presence of Gradle download'
  stat: path=/tmp/{{gradle_zipfile}}
  register: gradle_download
  when: features.gradle

- name: 'cleanup Gradle download'
  file: dest=/tmp/{{gradle_zipfile}} state=absent
  when: gradle_download.stat.exists
  
- name: 'make sure Gradle directory is absent'
  file: dest={{gradle_home}} state=absent
  when: not features.gradle
