---
  
- name: 'get the upstream yum repo file and store in /etc/yum.d'
  get_url: url={{jenkins_base_url}}/{{jenkins_repo}} dest=/etc/yum.repos.d/{{jenkins_repo}} owner=root group=root mode=0700
  when: ansible_os_family == "RedHat"
  
- name: 'authorize jenkins_repo for local rpm installs'
  command: rpm --import {{jenkins_pubkey}}
  when: ansible_os_family == "RedHat"
  
- name: 'make sure /opt is o+rx'
  file: path=/opt mode=0755
  
- name: 'check if jenkins_data directory exists'
  file: path={{jenkins_data}} owner=jenkins group=jenkins state=directory
  
- name: 'check if jenkins ~/.m2 directory exists'
  file: path={{jenkins_home}}/.m2 owner=jenkins group=jenkins mode=0750 state=directory
   
- name: 'add jenkins to group root for pam based authorization'
  shell: usermod -G root -a jenkins
  when: ansible_os_family == "RedHat" and features.system_auth
  
- name: 'allow jenkins to check passwords'
  file: path=/etc/shadow mode=0640
  when: ansible_os_family == "RedHat" and features.system_auth
  
- name: 'Create a 2048-bit SSH key for jenkins automation'
  user: name=jenkins generate_ssh_key=yes ssh_key_passphrase={{jenkins_phrase}} ssh_key_bits=2048
  
- name: 'restart jenkins on reboot'
  service: name=jenkins enabled=yes
  tags:
    - init
    - config
  notify:
    - 'start jenkins'  
