---
# Add Extra Packages for Enterprise Linux
- name: 'add EPEL yum repo'
  yum: name=epel-release state=present

# Allow managing under SELinux
- name: 'install python packages for Ansible'
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - libsemanage-python
   - python-httplib2
