---

- name: 'disable SELinux'
  shell: echo 0 >/selinux/enforce

- name: 'set SELinux to permissive'
  selinux: policy=targeted state=permissive

- name: 'set hostname'
  hostname: name={{ansible_hostname}}

- name: 'persist hostname'
  lineinfile: dest=/etc/sysconfig/network regexp='^HOSTNAME'
              line='HOSTNAME={{ansible_hostname}}' state=present

# avoid 'Could not retrieve mirrorlist' error 14: PYCURL ERROR 7 using ipv6 dns 
- name: 'add public resolver'
  lineinfile: dest=/etc/resolv.conf regexp='^nameserver' 
              line='nameserver 8.8.8.8' state=present
- name: 'disable ipv6'
  lineinfile: dest=/etc/sysconfig/network regexp='^NETWORKING_IPV6'
              line='NETWORKING_IPV6=no' state=present

# fix Virtualbox annoyances when commuting/roaming networks
- name: 'dissociate name of network adapter with MAC address.'
  shell: echo -n > /etc/udev/rules.d/70-persistent-net.rules
- name: 'avoid associating name of network adapter with MAC address.'
  shell: echo -n > /lib/udev/rules.d/75-persistent-net-generator.rules

