---

- name: 'install the postgres yum repo'
  yum: name={{postgres_repo}} state=present
  when: ansible_os_family == "RedHat"

- name: 'install postgres packages'
  yum: name={{ item }} state=present
  with_items: postgres_packages
  when: ansible_os_family == "RedHat"
